name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - 'embeddings/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'embeddings/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install bandit[toml]==1.7.*
    
    - name: Build embeddings index
      run: |
        python embeddings/build_index.py
    
    - name: Run tests
      run: |
        cd backend
        pytest -q
    
    - name: Security scan with Bandit
      run: |
        bandit -r backend -f json -o bandit-report.json -x backend/tests || true
        if [ -f bandit-report.json ]; then
          echo "Bandit security scan results:"
          python -m json.tool bandit-report.json
        fi
    
    - name: Dependency vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: 'backend'
        format: 'table'
        severity: 'HIGH,CRITICAL'
        exit-code: '0'  # Don't fail build, just report
      continue-on-error: true
    
    - name: Check code quality
      run: |
        cd backend
        python -m py_compile *.py